name: "secrets"
version: "3.8.4-dev"
usage: "Secrets encryption in Helm for Git storing"
description: |-
  This plugin provides secrets values encryption for Helm charts secure storing
useTunnel: false
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
platformCommand:
  - os: windows
    command: "cmd /c $HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd $HELM_PLUGIN_DIR\\scripts\\run.sh"

downloaders:
  - command: "scripts/run.sh downloader"
    protocols:
      - "sops"
      - "secret"
      - "secrets"
      - "gpg-import+secrets"
