name: "secrets"
version: "4.6.1-dev"
usage: "Secrets encryption in Helm for Git storing"
description: |-
  This plugin provides secrets values encryption for Helm charts secure storing
useTunnel: false
command: "sh '$HELM_PLUGIN_DIR/scripts/run.sh'"
platformCommand:
  - os: windows
    command: >-
      cmd /E:ON /V:ON /c !HELM_PLUGIN_DIR!\scripts\wrapper\run.cmd

downloaders:
  - command: "scripts/run.sh downloader"
    protocols:
      - "secrets"
      - "secrets+gpg-import"
      - "secrets+gpg-import-kubernetes"
      - "secrets+age-import"
      - "secrets+age-import-kubernetes"
      - "secrets+literal"
