name: 🐞 Bug
description: Something is not working as indended.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: |
        When I do <X>, <Y> happens and I see the error message attached below:
        ```...```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: When I do <X>, <Z> should happen instead.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - **Keycloak Version**: 10.0.1
        - **keycloak-config-cli Version**: 1.4.0
        - **Java Version**: 11
      value: |
        - Keycloak Version: [e.g. 10.0.1]
        - keycloak-config-cli Version: [e.g. 1.4.0]
        - Java Version: [e.g. 11]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
