#!/usr/bin/env bats

load '../lib/helper'
load '../lib/create_encrypted_file'
load '../bats/extensions/bats-support/load'
load '../bats/extensions/bats-assert/load'
load '../bats/extensions/bats-file/load'

@test "terraform: read valid file" {
    FILE="${TEST_TEMP_DIR}/assets/values/${HELM_SECRETS_DRIVER}/secrets.yaml"

    run helm secrets terraform "${FILE}"
    assert_success
    assert_output '{"content_base64":"Z2xvYmFsX3NlY3JldDogZ2xvYmFsX2JhcgprZXk6IHwtCiAgICAtLS0tLUJFR0lOIFBHUCBNRVNTQUdFLS0tLS0KCiAgICB3Y0ZNQXhZcHY0WVhLZkJBQVJBQVZ6RTcvRk1ENytVV3dNbHMyM3pLS0xvVHMrNXc5R012dWduMHdpNUtPSjhQCiAgICBQU3JSWTRyMjdWaHdRSDM4Z1dEcnpvM1JDbU85NDE0eFowSlcwSGFOMlBnZDNtbDZtWUNZLzVSRTdhcGdHWlFJCiAgICAzSW0wZnY4YmhJd2FQMlVXUHA3NEVYTHpBM21oMWRVdHd4bXVXT2VvU3ErVm01TnRiamtmVXQvNE1JY0Y1SUFZCiAgICBjK1U0Wk9kUWx6Z0V4d3UrVnRPcGVCcmt3ZmdsaDVmRnVLcU04RmcxSUlDaS9QcDZZQWxwQWRHcWx0MXpTNFBqCiAgICB5akFTNmVBdm5wTTBlQTVoU2h1b085SnNBdTRrVmphYUJsaXBWcGMxSTJ6ZGNUM0gvMWQ3QVN6aXdiS09tNmpFCiAgICBQSnh6YU1EeG4wVWZNamtoVGFUWjh2MjdsejZXN3FkbEhkQ1dHR0kzNDhRa1NvRG90bTdPek1DN1pMZnBzMys5CiAgICBHclhvOUt3eGtqNm95L3RobjkyVzJjUlNlU0QyOGc2a2NVa0hlRzhMM21NditncFRqSWhNK1o4eDNqSmNWcDJpCiAgICB5b0EyZE8va08yL0hUY1VmbkVqcHBLaWdxVWxSdUtmRG44ZXJjallpcStmb3F0aW1IMTkyaVhYeVJtbHRZbEgwCiAgICBHVVNKMUZjTkxBQzlnMFdMRlBRbk1GaDVLeFN3ZWF2cGJkZDZQSUxxRXN5S3ZacEM1YStoekxLd0dqV092ZVcxCiAgICBLMzRRWmY2QXkzQ1BDZWdBeUdWanhtc2cxdlBLRCs5V0FaaW52ZUNsMzdsM2NDUVcxVlp6YkdrSGd0TFEzMFFyCiAgICBEQ1JGWkVzdHJhTEFRVWY2VkxBazliUFlYL2Z2a1htcmE5NzBpL0NmSmpJZzBTcE9YYkFEQlI0eCt6UlJacXJTCiAgICA0QUhrV1RtaEgveFhXeUFnbWgrc0dzMThPT0ZHZmVDMDRBamhNbXZnNHVLemx5Nis0SURsTmhQaWYyVnBKWU9pCiAgICBFbVU4Z1FvVXNBSEtZcm8waFBmekJaeUpsTCtUcUNQZ0hlUlBBTlZnbTRXdzZSbFZyTkZwVHk5SDRtNHM1eS9oCiAgICBFekFBCiAgICA9amY3RAogICAgLS0tLS1FTkQgUEdQIE1FU1NBR0UtLS0tLQpzZXJ2aWNlOgogICAgcG9ydDogODE="}'
}

@test "terraform: read invalid file" {
    FILE="${TEST_TEMP_DIR}/assets/values/${HELM_SECRETS_DRIVER}/non-exists.yaml"

    run helm secrets terraform "${FILE}"
    assert_failure
    assert_output --partial '[helm-secrets] File does not exist:'
}
